/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Model.Book;
import Model.DatabaseConnection;
import controller.BookController;
import controller.MemberController;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AL MUBDIE
 */
public class MemberPage extends javax.swing.JFrame {

    private BookController bookController;

    public MemberPage() {
        initComponents();
        try {
            // Initialize controllers with the shared connection
            Connection connection = DatabaseConnection.getConnection();

            this.bookController = new BookController(connection);

            // Load the member table on initialization
            loadAllBooks();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error initializing database connection: " + e.getMessage());
        }

    }

    // Method to load all books into the table
    private void loadAllBooks() {
        try {
            DefaultTableModel model = (DefaultTableModel) tblBookSearch.getModel();
            model.setRowCount(0); // Clear existing rows
            List<Book> books = bookController.getAllBooks();
            for (Book book : books) {
                model.addRow(new Object[]{book.getBookID(), book.getTitle(), book.getAuthor(), book.getGenre(), book.getPublishedYear()});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading books: " + e.getMessage());
        }
    }

    // Method to handle book search based on title, author, and genre
    private void searchBooks() {
        String title = txtTitleSearch.getText().trim();
        String author = txtAuthorSearch.getText().trim();
        String genre = txtGenreSearch.getText().trim();

        if (title.isEmpty() && author.isEmpty() && genre.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter at least one search criteria!");
            return;
        }

        try {
            DefaultTableModel model = (DefaultTableModel) tblBookSearch.getModel();
            model.setRowCount(0); // Clear existing rows
            List<Book> books = bookController.searchBooks(title, author, genre);
            if (books.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No books found!");
            } else {
                for (Book book : books) {
                    model.addRow(new Object[]{book.getBookID(), book.getTitle(), book.getAuthor(), book.getGenre(), book.getPublishedYear()});
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error searching books: " + e.getMessage());
        }
    }

    private void resetFields() {
        txtTitleSearch.setText("");
        txtAuthorSearch.setText("");
        txtGenreSearch.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelMemberSearch = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblBookSearch = new rojeru_san.complementos.RSTableMetro();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTitleSearch = new rojerusan.RSMetroTextPlaceHolder();
        txtAuthorSearch = new rojerusan.RSMetroTextPlaceHolder();
        txtGenreSearch = new rojerusan.RSMetroTextPlaceHolder();
        btnSearch = new necesario.RSMaterialButtonCircle();
        imgSearch = new rojerusan.RSLabelImage();
        rSPanelImage1 = new rojerusan.RSPanelImage();
        btnSearchPanel = new rojeru_san.complementos.RSButtonHover();
        btnLogout = new rojeru_san.complementos.RSButtonHover();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBookSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "BookID", "Title", "Author", "Genre", "YearPublished"
            }
        ));
        tblBookSearch.setColorBackgoundHead(new java.awt.Color(51, 51, 51));
        tblBookSearch.setColorBordeFilas(new java.awt.Color(0, 112, 192));
        tblBookSearch.setColorBordeHead(new java.awt.Color(0, 44, 76));
        tblBookSearch.setColorFilasBackgound1(new java.awt.Color(0, 0, 81));
        tblBookSearch.setColorFilasBackgound2(new java.awt.Color(0, 0, 81));
        tblBookSearch.setColorFilasForeground1(new java.awt.Color(89, 255, 255));
        tblBookSearch.setColorFilasForeground2(new java.awt.Color(89, 255, 255));
        tblBookSearch.setColorForegroundHead(new java.awt.Color(89, 255, 255));
        tblBookSearch.setColorSelForeground(new java.awt.Color(0, 0, 0));
        tblBookSearch.setFont(new java.awt.Font("Source Sans 3 Medium", 0, 15)); // NOI18N
        tblBookSearch.setFuenteFilas(new java.awt.Font("Source Sans 3 Light", 1, 15)); // NOI18N
        tblBookSearch.setFuenteFilasSelect(new java.awt.Font("Source Sans 3 Light", 1, 15)); // NOI18N
        tblBookSearch.setFuenteHead(new java.awt.Font("Source Sans 3 SemiBold", 1, 15)); // NOI18N
        tblBookSearch.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tblBookSearch.setRowHeight(25);
        tblBookSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBookSearchMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tblBookSearch);

        jPanel3.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 190, 810, 430));

        jLabel1.setFont(new java.awt.Font("Source Sans 3 ExtraBold", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(89, 104, 215));
        jLabel1.setText("Book Title");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 100, 36));

        jLabel2.setFont(new java.awt.Font("Source Sans 3 ExtraBold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(89, 104, 215));
        jLabel2.setText("Book Author");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, 100, 36));

        jLabel3.setFont(new java.awt.Font("Source Sans 3 ExtraBold", 0, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(89, 104, 215));
        jLabel3.setText("Book Genre");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 100, -1));

        txtTitleSearch.setBackground(new java.awt.Color(0, 0, 81));
        txtTitleSearch.setForeground(new java.awt.Color(89, 255, 255));
        txtTitleSearch.setBorderColor(new java.awt.Color(89, 40, 237));
        txtTitleSearch.setFont(new java.awt.Font("Source Sans 3 Light", 1, 14)); // NOI18N
        txtTitleSearch.setPhColor(new java.awt.Color(89, 255, 255));
        txtTitleSearch.setPlaceholder("Enter Book Name");
        jPanel3.add(txtTitleSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 230, 40));

        txtAuthorSearch.setBackground(new java.awt.Color(0, 0, 81));
        txtAuthorSearch.setForeground(new java.awt.Color(89, 255, 255));
        txtAuthorSearch.setBorderColor(new java.awt.Color(89, 40, 237));
        txtAuthorSearch.setFont(new java.awt.Font("Source Sans 3 Light", 1, 14)); // NOI18N
        txtAuthorSearch.setPhColor(new java.awt.Color(89, 255, 255));
        txtAuthorSearch.setPlaceholder("Enter Author Name");
        jPanel3.add(txtAuthorSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 230, 40));

        txtGenreSearch.setBackground(new java.awt.Color(0, 0, 81));
        txtGenreSearch.setForeground(new java.awt.Color(89, 255, 255));
        txtGenreSearch.setBorderColor(new java.awt.Color(89, 40, 237));
        txtGenreSearch.setFont(new java.awt.Font("Source Sans 3 Light", 1, 14)); // NOI18N
        txtGenreSearch.setPhColor(new java.awt.Color(89, 255, 255));
        txtGenreSearch.setPlaceholder("Enter Genre");
        jPanel3.add(txtGenreSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 230, 40));

        btnSearch.setText("Search");
        btnSearch.setFont(new java.awt.Font("Source Sans 3 ExtraBold", 0, 12)); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        jPanel3.add(btnSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 60, 50));

        imgSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/bg/1000_F_171744995_u4KjXeKS61D3oxApKNHpJkKV81iA7dSs.jpg"))); // NOI18N
        jPanel3.add(imgSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -10, 850, 690));

        panelMemberSearch.addTab("tab1", jPanel3);

        jPanel1.add(panelMemberSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(141, -26, 820, 670));

        rSPanelImage1.setImagen(new javax.swing.ImageIcon(getClass().getResource("/Images/bg/panelbg.jpg"))); // NOI18N
        rSPanelImage1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSearchPanel.setBackground(new java.awt.Color(89, 40, 237));
        btnSearchPanel.setForeground(new java.awt.Color(89, 40, 237));
        btnSearchPanel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search.png"))); // NOI18N
        btnSearchPanel.setText("Search");
        btnSearchPanel.setFont(new java.awt.Font("Source Sans 3", 1, 18)); // NOI18N
        btnSearchPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchPanelMouseClicked(evt);
            }
        });
        rSPanelImage1.add(btnSearchPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 150, 37));

        btnLogout.setBackground(new java.awt.Color(0, 0, 81));
        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/logout.png"))); // NOI18N
        btnLogout.setText("LogOut");
        btnLogout.setFont(new java.awt.Font("Source Sans 3", 1, 18)); // NOI18N
        btnLogout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLogoutMouseClicked(evt);
            }
        });
        rSPanelImage1.add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 450, 150, 37));

        jLabel4.setFont(new java.awt.Font("Source Sans 3 ExtraBold", 0, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(89, 104, 215));
        jLabel4.setText("WelCome");
        rSPanelImage1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 80, 30));

        jLabel5.setFont(new java.awt.Font("Source Sans 3 ExtraBold", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(89, 104, 215));
        jLabel5.setText("Member");
        rSPanelImage1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 110, 36));

        jPanel1.add(rSPanelImage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchPanelMouseClicked
        // TODO add your handling code here:
        panelMemberSearch.setSelectedIndex(0);
    }//GEN-LAST:event_btnSearchPanelMouseClicked

    private void btnLogoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLogoutMouseClicked
        // TODO add your handling code here:
        int response = javax.swing.JOptionPane.showConfirmDialog(this, "Do you really want to log out?", "Confirm Logout", javax.swing.JOptionPane.YES_NO_OPTION);

        if (response == javax.swing.JOptionPane.YES_OPTION) {
            MemberLogin memberLogin = new MemberLogin();
            memberLogin.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_btnLogoutMouseClicked

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        searchBooks();
    }//GEN-LAST:event_btnSearchMouseClicked

    private void tblBookSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBookSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBookSearchMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.complementos.RSButtonHover btnLogout;
    private necesario.RSMaterialButtonCircle btnSearch;
    private rojeru_san.complementos.RSButtonHover btnSearchPanel;
    private rojerusan.RSLabelImage imgSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane panelMemberSearch;
    private rojerusan.RSPanelImage rSPanelImage1;
    private rojeru_san.complementos.RSTableMetro tblBookSearch;
    private rojerusan.RSMetroTextPlaceHolder txtAuthorSearch;
    private rojerusan.RSMetroTextPlaceHolder txtGenreSearch;
    private rojerusan.RSMetroTextPlaceHolder txtTitleSearch;
    // End of variables declaration//GEN-END:variables
}
